{% set name = "nb-clean" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8f3d494c8c6075fbaab5fc379f933c4295c18d0e09d078ae6f006cd3ee707cd5

build:
  entry_points:
    - nb-clean = nb_clean.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
  run:
    - nbformat >=5.1.2,<6.0.0
    - python >=3.6,<4.0

test:
  imports:
    - nb_clean
  commands:
    - pip check
    - nb-clean --help
  requires:
    - pip

about:
  home: https://github.com/srstevenson/nb-clean
  summary: Clean Jupyter notebooks for versioning
  license: ISC
  license_file: LICENCE

extra:
  recipe-maintainers:
    - srstevenson
    - ukukas
