{% set name = "nb-clean" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nb-clean-{{ version }}.tar.gz
  sha256: 6e890fae7989e74bb0efc5bbe696947dc1667439b1dad3376911af0d3254e86a

build:
  entry_points:
    - nb-clean = nb_clean.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
  run:
    - nbformat >=5.1.2,<6.0.0
    - python >=3.6,<4.0

test:
  imports:
    - nb_clean
  commands:
    - pip check
    - nb-clean --help
  requires:
    - pip

about:
  home: https://github.com/srstevenson/nb-clean
  summary: Clean Jupyter notebooks for versioning
  license: ISC
  license_file: LICENCE

extra:
  recipe-maintainers:
    - srstevenson
    - ukukas
